require("config.lazy")
require("config.options")
require("config.theme")
require("config.mason")
require("config.harpoon")
require("config.iron")
require("config.markdown")
require("config.split")
